POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "chapengu",
    "password": "123",
    "email": "chapp@gamil.com",
    "teamname": "pepe"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "chapp@gamil.com"
}

###

GET http://localhost:3000/api/auth/players HTTP/1.1

POST http://localhost:3000/api/auth/players HTTP/1.1
Content-Type: application/json

{
    "players": [
        {
          "apellido": "chaparro",
          "categoria": "del",
          "nombre": "lautaro",
          "precio": 5.5
        },
        {
          "apellido": "moschen",
          "categoria": "del",
          "nombre": "sebastian",
          "precio": 5.5
        },
        {
          "apellido": "ferro",
          "categoria": "mc",
          "nombre": "tiziano",
          "precio": 5.5
        },
        {
          "apellido": "jerez",
          "categoria": "mc",
          "nombre": "agustin",
          "precio": 5.5
        },
        {
          "apellido": "dular",
          "categoria": "df",
          "nombre": "tomas",
          "precio": 5.5
        },
        {
          "apellido": "dibello",
          "categoria": "df",
          "nombre": "romeo",
          "precio": 5.5
        },
        {
          "apellido": "moschen",
          "categoria": "pt",
          "nombre": "christian",
          "precio": 5.5
        },
        {
          "apellido": "quinteros",
          "categoria": "mc",
          "nombre": "matias",
          "precio": 5.5
        },
        {
          "apellido": "dimitrioff",
          "categoria": "df",
          "nombre": "facundo",
          "precio": 5.5
        }
    ]
}

###

POST http://localhost:3000/api/transferencia/1 HTTP/1.1
Content-Type: application/json

{
    "players": [
        {
            "ID_Jugador": 1,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 2,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 3,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 4,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 5,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 6,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 7,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 8,
            "order": 0,
            "estaEnBanca": true,
            "esCapitan": false,
            "precio": 5.0
        },
        {
            "ID_Jugador": 9,
            "order": 1,
            "estaEnBanca": true,
            "esCapitan": false,
            "precio": 5.0
        }
    ]
}

###

POST http://localhost:3000/api/cambiar/1 HTTP/1.1
Content-Type: application/json

{
    "players": [
        {
            "ID_Jugador": 1,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 2,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": true
        },
        {
            "ID_Jugador": 3,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 4,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 5,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 6,
            "order": 1,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 7,
            "order": 0,
            "estaEnBanca": false,
            "esCapitan": false
        },
        {
            "ID_Jugador": 8,
            "order": 0,
            "estaEnBanca": true,
            "esCapitan": false
        },
        {
            "ID_Jugador": 9,
            "order": 1,
            "estaEnBanca": true,
            "esCapitan": false
        }
    ]
}