GET http://localhost:3000/api HTTP/1.1

######

GET http://localhost:3000/api/cuenta HTTP/1.1

#####

GET http://localhost:3000/api/cuenta/20 HTTP/1.1

#####

DELETE http://localhost:3000/api/cuenta/4 HTTP/1.1

#####

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "javi1252",
    "password": "12345678",
    "email": "javi@gmail.com",
    "teamname": "wollok"
}

####

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "javi@gmail.com",
    "password": "12345678"
}

####

GET http://localhost:3000/api/jugador/91 HTTP/1.1

####

GET http://localhost:3000/api/jugador HTTP/1.1


####
PATCH http://localhost:3000/api/equipo/1 HTTP/1.1
transfer: 0
Content-Type: application/json

{
    "teamname" : "WollokCF"
}

#### el siguiente GET debe devolver los datos de la tabla equipo del id seleccionado, 
###la alineacion no debe pasar IDs, debe pasar los objeto jugador con su ultima
#### fila de stats

GET http://localhost:3000/api/equipo/31 HTTP/1.1

#### idem del anterior pero se devuelven todos los equipos
GET http://localhost:3000/api/equipo HTTP/1.1


### este metodo debe crear un equipo nuevo (copia de carbono del anterior)
PUT http://localhost:3000/api/equipo HTTP/1.1

### edita la alineacion y otras cosas relacionadas al equipo

PATCH  http://localhost:3000/api/equipo/32 HTTP/1.1
Content-Type: application/json
transfer: 1

## la lista de cant de transferencias refiere a los ID de aquellos que fueron transferidos

{
    "cantTransfers" : [91, 92],
    "budget": 100,
    "players": [
        {
          "ID_Jugador": 91,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 96,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 97,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 98,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 106,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 107,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 108,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 116,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        },
        {
          "ID_Jugador": 117,
          "playerOrder": 0,
          "estaEnBanca": false,
          "esCapitan": false
        }
    ]
}

###
PUT http://localhost:3000/api/stat/91 HTTP/1.1
Content-Type: application/json

{
  "goals" : 3,
  "assists" : 2,
  "interceptions" : 5,
  "saves" : 10,
  "failedPenalties" : 0,
  "savedPenalties" : 0,
  "assistance" : true
}